version: '3'
services:
  client:
    image: node:16
    container_name: project_client1
    ports: 
      - 8080:8080
    volumes:
      - type: bind
        source: ./client/client
        target: /code2
    working_dir: /code2
    command: bash -c "npm install && npm run dev"
    # depends on:
    #   - api


  api: 
    image: node:18
    container_name: project_server1
    ports: 
      - 3000:3000
    volumes:
      - type: bind
        source: ./server/server
        target: /code1
    working_dir: /code1cd
    command: bash -c "npm install && npm run dev"